### ISSUE TITLE
html lang=".." instead of body lang=".."

### ISSUE THREAD

**Issue by Hexagon** [brocococonut/freshlate#1]
Hi!

First - thanks for a great little library :)

As it seem impossible to properly set body lang=".." in fresh, and as html lang=".." is a standard feature. Wouldn't it be better to use html lang=".." instead?

https://github.com/brocococonut/freshlate/blob/ac12cc5fddde4f3e0e34e44fb4bcd65d81906b52/freshlate/main.ts#L10

That line could be changed to 
```javascript
let language = document.documentElement.lang;
```

html lang=".." is set by
```javascript
await start(
    manifest,
    {
        plugins: [languagePlugin({ ...languageConfig })],
        render: (ctx, render) => {
            ctx.lang = "sv"
            render();
        }
    }
);
```

While body lang=".." seem to be impossible to set, as fresh injects a clean <body> tag before any tsx is rendered, if you pass `<body lang="sv">` as tsx, the actual output seem to be `<body><body lang="sv">`

**Comment by Hexagon** [comment]
Hmm, html lang is application wide - cannot be changed per route. So maybe it's just usable as an additional fallback. 

But anyhow, body lang seem to be a bad choice for per route languages, maye there is another (better) option?

**Comment by brocococonut** [comment]
Hey there!

Thanks for the first issue!
I was actually just thinking that a better route might be to use a "set-lang" property (or something similar) on any given tag and keep it as the current language until it reaches another set-lang. The main issue I can forsee doing it this way is it wouldn't necessarily be cascading like CSS would, but instead would be sequential and could be a bit messy when used across components. It would allow for customising the language used per route though.

As each request is server rendered, it might be best to just split the handling of what language to use off to the server, and set all subsequent renders that are client side to the one language based on what the server provides. It won't be reactive that way though 🤔

There's pitfalls with most ways of doing it unfortunately. I actually spun the translation library off into a separate package in my own code and was just using that with svelte to be completely honest 😅 I definitely should update and maintain this though.

**Comment by brocococonut** [comment]
The repo has been migrated over to https://github.com/locale-kit/locale-kit and https://github.com/locale-kit/locale-kit-fresh :)
Lemme know if that works for ya!
